name: it_planet_first
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.4.0
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  share_plus: ^10.1.4
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.10.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.1
  # http: ^1.3.0
  flutter_web_auth: ^0.6.0
  github_sign_in_plus: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/icons/bottom_nav_bar/
    - .env

  fonts:
    - family: KremlinCTT
      fonts:
        - asset: assets/fonts/KremlinCTT/KremlinCTT.ttf

    - family: iosevka
      fonts:
        - asset: assets/fonts/iosevka/iosevka-regular.ttf
          weight: 400
        - asset: assets/fonts/iosevka/iosevka-bold.ttf
          weight: 700
        - asset: assets/fonts/iosevka/iosevka-thin.ttf
          weight: 100
        - asset: assets/fonts/iosevka/iosevka-light.ttf
          weight: 300
        - asset: assets/fonts/iosevka/iosevka-medium.ttf
          weight: 500
        - asset: assets/fonts/iosevka/iosevka-semibold.ttf
          weight: 600
        - asset: assets/fonts/iosevka/iosevka-extrabold.ttf
          weight: 800
        - asset: assets/fonts/iosevka/iosevka-heavy.ttf
          weight: 900
        - asset: assets/fonts/iosevka/iosevka-italic.ttf
          style: italic
        - asset: assets/fonts/iosevka/iosevka-bolditalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/iosevka/iosevka-thinitalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/iosevka/iosevka-lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/iosevka/iosevka-mediumitalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/iosevka/iosevka-semibolditalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/iosevka/iosevka-extrabolditalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/iosevka/iosevka-heavyitalic.ttf
          weight: 900
          style: italic

    


