// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5LIr7j6g7O5mvMPncV6EatNkP8QGIOi0',
    appId: '1:638515874961:web:1c020a3a79aed941444330',
    messagingSenderId: '638515874961',
    projectId: 'it-planet-1',
    authDomain: 'it-planet-1.firebaseapp.com',
    storageBucket: 'it-planet-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmsUG2UOzHpDnk6Tnqsi95ZfWfH1WLy7A',
    appId: '1:638515874961:android:3cb473eca7f13ebb444330',
    messagingSenderId: '638515874961',
    projectId: 'it-planet-1',
    storageBucket: 'it-planet-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-FtcMBRjEfvh_K0CifEn4I_anJ7w5CZQ',
    appId: '1:638515874961:ios:147042a43b015418444330',
    messagingSenderId: '638515874961',
    projectId: 'it-planet-1',
    storageBucket: 'it-planet-1.firebasestorage.app',
    iosBundleId: 'com.example.itPlanetFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-FtcMBRjEfvh_K0CifEn4I_anJ7w5CZQ',
    appId: '1:638515874961:ios:147042a43b015418444330',
    messagingSenderId: '638515874961',
    projectId: 'it-planet-1',
    storageBucket: 'it-planet-1.firebasestorage.app',
    iosBundleId: 'com.example.itPlanetFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5LIr7j6g7O5mvMPncV6EatNkP8QGIOi0',
    appId: '1:638515874961:web:32dfaae5ce3fb1cf444330',
    messagingSenderId: '638515874961',
    projectId: 'it-planet-1',
    authDomain: 'it-planet-1.firebaseapp.com',
    storageBucket: 'it-planet-1.firebasestorage.app',
  );
}
